name: Blockjs
version: '${version}'
main: com.violeth.blockjs.blockjs.Blockjs
api-version: 1.15
authors: [ Violet ]
description: A Paper plugin to use JavaScript to interact with your Minecraft world
